language: node_js
os: linux
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - npm install peers
  - rm -f package-lock.json && npm install
  - npm test
  - npm run build
  - cd build
  - cp index.html 200.html
deploy:
  provider: surge
  skip_cleanup: true
  domain: asylumcesiweb.surge.sh
  project: ./build/
  on:
    branch: master
